# Generated by Django 3.2 on 2021-07-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='petregister',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='petregister',
            name='pettype',
            field=models.CharField(max_length=100),
        ),
    ]
