# Generated by Django 3.2 on 2021-07-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210702_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='petregister',
            name='pettype',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Fish', 'Fish'), ('Turtle', 'Turtle'), ('Horse', 'Horse')], max_length=100),
        ),
    ]
