# Generated by Django 3.2 on 2021-07-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='photo',
            field=models.ImageField(upload_to='petboarding'),
        ),
        migrations.AlterField(
            model_name='petregister',
            name='photo',
            field=models.ImageField(upload_to='petboarding'),
        ),
    ]
