# Generated by Django 3.2.5 on 2021-07-09 07:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20210702_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pettype', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Fish', 'Fish'), ('Turtle', 'Turtle'), ('Horse', 'Horse')], max_length=100)),
                ('photo', models.ImageField(upload_to='pets')),
                ('age', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('specialinstruction', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=50)),
                ('dob', models.DateField(max_length=10)),
                ('photo', models.ImageField(upload_to='profile')),
                ('altcontact', models.CharField(max_length=12)),
                ('address', models.TextField(max_length=80)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Complaints',
            new_name='Complaint',
        ),
        migrations.RemoveField(
            model_name='petregister',
            name='user',
        ),
        migrations.AlterField(
            model_name='boarding',
            name='chargeamount',
            field=models.FloatField(default=100.0),
        ),
        migrations.AlterField(
            model_name='boarding',
            name='duration',
            field=models.PositiveIntegerField(help_text='enter number of days'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.DeleteModel(
            name='PetRegister',
        ),
        migrations.AddField(
            model_name='boarding',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boardings', to='app.pet'),
        ),
    ]
