# Generated by Django 3.2.5 on 2021-07-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210709_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarding',
            name='pet',
        ),
        migrations.AddField(
            model_name='boarding',
            name='pet',
            field=models.ManyToManyField(related_name='boardings', to='app.Pet'),
        ),
    ]
