# Generated by Django 3.2.5 on 2021-07-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210709_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarding',
            name='is_pet_dlv_back',
        ),
        migrations.AddField(
            model_name='boarding',
            name='pick_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='boarding',
            name='status',
            field=models.CharField(choices=[('Preparing', 'preparing'), ('Pickup', 'pickup'), ('delivered', 'delivered'), ('Boarded', 'boarded'), ('on the way', 'on the way')], default='Preparing', max_length=20),
        ),
    ]
