# Generated by Django 3.2.3 on 2021-07-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210709_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='boarding',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.boarding'),
            preserve_default=False,
        ),
    ]
