# Generated by Django 3.2.5 on 2021-07-10 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210710_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='boarding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.boarding'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('payment gateway', 'payment gateway')], max_length=30),
        ),
    ]
